POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "Uudempi Testi Blogi",
"author": "Kirjoittaja",
"url": "www.bloginen.com",
"likes": 3,
"userId": "603a295c51e3c2a93826367d"
}